### ISSUE TITLE
Link da lista de exercícios.

### ISSUE THREAD

**Issue by matheusdsm** [mshmeirelles/google-python-exercises#1]
Heeeey cara :D 

Fiquei interessado nos desafios, porém quero fazer as versões em Vanilla JS.

Gostaria de saber se você possui a lista de exercícios? ou melhor, o link da lista?

Obrigado =]

**Comment by mshmeirelles** [comment]
Opa Brother!

Legal, nos exercícios tem a descrição, eu vou acompanhar eles pelos próprios arquivos .py
Mas você pode encontrar o link aqui: https://developers.google.com/edu/python/exercises/basic

Qualquer coisa, só chamar ae :)
